/* eslint-disable camelcase */
// Generated by https://quicktype.io

import { SingleResponse, Link } from './common';

export type PersonalBestResponse = SingleResponse<Datum[]>;

export interface Datum {
  place: number;
  run: Run;
}

export interface Run {
  id: string;
  weblink: string;
  game: string;
  level: null;
  category: string;
  videos: Videos | null;
  comment: null | string;
  status: StatusClass;
  players: Player[];
  date: string;
  submitted: string;
  times: Times;
  system: System;
  splits: Link | null;
  values: { [key: string]: string };
  links: Link[];
}

export interface Player {
  rel: string;
  id: string;
  uri: string;
}

export interface StatusClass {
  status: string;
  examiner: string;
  'verify-date': string;
}

export interface System {
  platform: string;
  emulated: boolean;
  region: null;
}

export interface Times {
  primary: string;
  primary_t: number;
  realtime: string;
  realtime_t: number;
  realtime_noloads: null;
  realtime_noloads_t: number;
  ingame: string;
  ingame_t: number;
}

export interface Videos {
  links: VideosLink[];
}

export interface VideosLink {
  uri: string;
}
