// Generated by https://quicktype.io

export interface UserResponse {
  data: Data;
}

export interface UsersResponse {
  data: Data[];
  pagination: Pagination;
}

export interface Pagination {
  offset: number;
  max: number;
  size: number;
  links: Link[];
}

export interface Data {
  id: string;
  names: Names;
  weblink: string;
  'name-style': NameStyle;
  role: string;
  signup: string;
  location: Location;
  twitch: SocialAccount | null;
  hitbox: SocialAccount | null;
  youtube: SocialAccount | null;
  twitter: SocialAccount | null;
  speedrunslive: SocialAccount | null;
  links: Link[];
}

export interface Link {
  rel: string;
  uri: string;
}

export interface Location {
  country: Country;
  region: Country;
}

export interface Country {
  code: string;
  names: Names;
}

export interface Names {
  international: string;
  japanese: null;
}

export interface NameStyle {
  style: string;
  'color-from': Color;
  'color-to': Color;
}

export interface Color {
  light: string;
  dark: string;
}

export interface SocialAccount {
  uri: string;
}
